# Generated by Django 5.1.4 on 2025-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('limit', models.IntegerField(blank=True, default='30', null=True)),
                ('is_bloked', models.BooleanField(default=False)),
            ],
        ),
    ]
